import { useEffect, useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { FolderOpen } from "lucide-react";
import { listDocuments, saveDocument, documentFile, updateDocument, type SavedDocument } from "../lib/library";
import { useDocumentStore } from "../store/useDocumentStore";
import { Dropzone } from "../components/Dropzone";
import { formatSize } from "../lib/formatSize";
import { friendlyError } from "../lib/importFiles";
export default function FilesPage(){const [docs,setDocs]=useState<SavedDocument[]>([]);const [loaded,setLoaded]=useState(false);const [query,setQuery]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const navigate=useNavigate();const current=useDocumentStore(s=>s.current);
 const refresh=async()=>{try{setDocs(await listDocuments());}catch(e){setError(friendlyError(e));}finally{setLoaded(true);}};
 useEffect(()=>{void refresh();},[]);
 const save=async(file:File)=>{if(busy)return;setBusy(true);try{await saveDocument(file);await refresh();}catch(e){setError(friendlyError(e));}finally{setBusy(false);}};
 return <section><h1 className="text-3xl font-bold">My files</h1><p className="mt-2 text-muted">Saved only on this device. Export important files as a backup.</p>{current&&<div className="panel mt-4"><p className="truncate">Current: {current.name}</p><button disabled={busy} className="btn mt-3" onClick={()=>void save(current)}>Save current document on device</button></div>}<div className="mt-5"><Dropzone accept="application/pdf,image/*" multiple={false} label="Import and save a file" hint="This keeps a local copy on your device" onFiles={files=>void save(files[0])}/></div><input className="field mt-4" aria-label="Search saved files" placeholder="Search files" value={query} onChange={e=>setQuery(e.target.value)}/>{error&&<p role="alert" className="text-bad mt-3">{error}</p>}<div className="mt-4 space-y-3">{!loaded?<p role="status">Loading files…</p>:docs.filter(d=>!d.deletedAt&&(d.name+d.folder).toLowerCase().includes(query.toLowerCase())).map(doc=><article className="panel" key={doc.id}><button className="w-full text-left" onClick={()=>{useDocumentStore.getState().setCurrent(documentFile(doc));navigate("/document");}}><strong className="block break-words">{doc.name}</strong><span className="text-sm text-muted">{formatSize(doc.size)} · {new Date(doc.updatedAt).toLocaleDateString()}</span></button><button className="btn-secondary mt-3" onClick={async()=>{try{await updateDocument({...doc,deletedAt:Date.now()});await refresh();}catch(e){setError(friendlyError(e));}}}>Move to trash</button></article>)}</div>{loaded&&!docs.some(d=>!d.deletedAt)&&<div className="panel mt-4 text-center"><FolderOpen className="mx-auto mb-2"/><h2>Your files will appear here</h2><Link className="btn mt-3" to="/scan">Scan a document</Link></div>}<Link className="inline-block mt-5 text-accent" to="/scans">Previously saved scans →</Link></section>}
