import { useEffect, useState } from "react";
import { useDocumentStore } from "../store/useDocumentStore";
import { Dropzone } from "../components/Dropzone";
import { downloadBlob } from "../lib/download";
import { friendlyError } from "../lib/importFiles";
import { formatSize } from "../lib/formatSize";
export default function ImagePage(){const file=useDocumentStore(s=>s.current);const [url,setUrl]=useState("");const [rotation,setRotation]=useState(0);const [width,setWidth]=useState(1600);const [crop,setCrop]=useState(0);const [quality,setQuality]=useState(0.85);const [format,setFormat]=useState("image/jpeg");const [result,setResult]=useState<Blob|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{setResult(null);if(!file?.type.startsWith("image/"))return;const u=URL.createObjectURL(file);setUrl(u);return()=>URL.revokeObjectURL(u);},[file]);
 const build=async()=>{if(!file||busy)return;setBusy(true);setError("");try{const b=await createImageBitmap(file);const inset=Math.min(0.4,Math.max(0,crop/100));const sw=b.width*(1-2*inset),sh=b.height*(1-2*inset);const c=document.createElement("canvas");const rotated=rotation%180!==0;const ratio=Math.min(1,width/(rotated?sh:sw));c.width=Math.round((rotated?sh:sw)*ratio);c.height=Math.round((rotated?sw:sh)*ratio);const ctx=c.getContext("2d")!;if(format==="image/jpeg"){ctx.fillStyle="white";ctx.fillRect(0,0,c.width,c.height);}ctx.translate(c.width/2,c.height/2);ctx.rotate(rotation*Math.PI/180);ctx.drawImage(b,b.width*inset,b.height*inset,sw,sh,-sw*ratio/2,-sh*ratio/2,sw*ratio,sh*ratio);b.close();const out=await new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error("This format is unsupported in your browser.")),format,quality));setResult(out);const ext=format.split("/")[1].replace("jpeg","jpg");downloadBlob(out,file.name.replace(/\.[^.]+$/,"")+"-edited."+ext);}catch(e){setError(friendlyError(e));}finally{setBusy(false);}};
 return <section><h1 className="text-2xl font-bold">Edit & compress image</h1><p className="text-muted mt-2">Crop edges, rotate, resize and convert. Your original image stays on your device.</p><div className="mt-4"><Dropzone accept="image/*" label="Choose a photo" hint={file?.type.startsWith("image/")?file.name:"JPG, PNG, WebP, GIF or BMP"} onFiles={f=>useDocumentStore.getState().setCurrent(f[0])}/></div>{url&&file?.type.startsWith("image/")&&<><img className="mt-4 max-h-[40vh] mx-auto object-contain" src={url} alt="Original image"/><div className="editor-options"><label className="field-label">Rotation<select className="field" value={rotation} onChange={e=>setRotation(Number(e.target.value))}>{[0,90,180,270].map(r=><option key={r} value={r}>{r}°</option>)}</select></label><label className="field-label">Trim each edge (%)<input className="field" type="number" min="0" max="40" value={crop} onChange={e=>setCrop(Math.max(0,Math.min(40,Number(e.target.value))))}/></label><label className="field-label">Maximum width (px)<input className="field" type="number" min="100" max="6000" value={width} onChange={e=>setWidth(Math.max(100,Math.min(6000,Number(e.target.value)||1600)))}/></label><label className="field-label">Format<select className="field" value={format} onChange={e=>setFormat(e.target.value)}><option value="image/jpeg">JPEG</option><option value="image/png">PNG (lossless)</option><option value="image/webp">WebP</option></select></label><label className="field-label">Quality<input type="range" min="0.2" max="1" step="0.05" value={quality} onChange={e=>setQuality(Number(e.target.value))}/></label></div><button className="btn" data-primary-action disabled={busy} onClick={()=>void build()}>{busy?"Processing…":"Export image"}</button>{result&&<p role="status">Original {formatSize(file.size)} → result {formatSize(result.size)}</p>}</>}{error&&<p role="alert" className="text-bad">{error}</p>}</section>;
}
