import test from "node:test";
import assert from "node:assert/strict";
import { PDFDocument, degrees } from "pdf-lib";
import { editPdf, readForms, screenPoint } from "../src/lib/pdf/edit.ts";
import { buildOrganizedPdf } from "../src/lib/pdf/organize.ts";
import { applyWatermark } from "../src/lib/pdf/watermark.ts";
import { applyPageNumbers } from "../src/lib/pdf/pageNumbers.ts";
async function fixture(){const d=await PDFDocument.create();const p=d.addPage([600,800]);p.setCropBox(20,30,560,740);p.setRotation(degrees(90));const f=d.getForm().createTextField("Full name");f.setText("Before");f.addToPage(p,{x:50,y:60,width:180,height:30});const c=d.getForm().createCheckBox("Accept");c.addToPage(p,{x:50,y:120,width:20,height:20});d.addPage([600,800]);return d.save();}
test("editor fills interactive forms and optional flatten removes fields",async()=>{const bytes=await fixture();const values=await readForms(bytes);values.find(f=>f.name==="Full name").value="Alice";values.find(f=>f.name==="Accept").value=true;const filled=await PDFDocument.load(await editPdf(bytes,[],values,false));assert.equal(filled.getForm().getTextField("Full name").getText(),"Alice");assert.ok(filled.getForm().getCheckBox("Accept").isChecked());assert.equal(filled.getPage(0).getRotation().angle,90);assert.deepEqual(filled.getPage(0).getCropBox(),{x:20,y:30,width:560,height:740});const flat=await PDFDocument.load(await editPdf(bytes,[],values,true));assert.equal(flat.getForm().getFields().length,0);assert.equal(flat.getPageCount(),2);});
test("annotation coordinates respect crop origin and all right angle rotations",()=>{const b={x:20,y:30,width:560,height:740};assert.deepEqual(screenPoint(b,0,0,0),[20,770]);assert.deepEqual(screenPoint(b,90,0,0),[20,30]);assert.deepEqual(screenPoint(b,180,0,0),[580,30]);assert.deepEqual(screenPoint(b,270,0,0),[580,770]);assert.deepEqual(screenPoint(b,90,1,1),[580,770]);});
test("organize duplicates, crops and adds user rotation on top of original",async()=>{const b=await fixture();const out=await PDFDocument.load(await buildOrganizedPdf(b.buffer,[90,0],[{id:"a",index:1,rotation:0},{id:"b",index:0,rotation:90,crop:10},{id:"c",index:0,rotation:0}]));assert.equal(out.getPageCount(),3);assert.equal(out.getPage(1).getRotation().angle,180);assert.deepEqual(out.getPage(1).getCropBox(),{x:76,y:104,width:448,height:592});});
test("watermark ranges reject out-of-bounds input and retain original geometry",async()=>{const b=await fixture();await assert.rejects(applyWatermark(b.buffer,{text:"Draft",opacity:.4,fontSize:24,rotation:0,ranges:"3"}));const d=await PDFDocument.load(await applyWatermark(b.buffer,{text:"Draft",opacity:.4,fontSize:24,rotation:30,ranges:"2"}));assert.equal(d.getPageCount(),2);assert.equal(d.getPage(0).getRotation().angle,90);});
test("number ranges reject invalid pages without producing an output",async()=>{const b=await fixture();await assert.rejects(applyPageNumbers(b.buffer,{position:"bottom-center",format:"number",startAt:1,fontSize:12,ranges:"0"}));const d=await PDFDocument.load(await applyPageNumbers(b.buffer,{position:"bottom-center",format:"number",startAt:1,fontSize:12,skipCover:true,prefix:"Page "}));assert.equal(d.getPageCount(),2);});
