import { PDFDocument, PDFTextField, PDFCheckBox, PDFDropdown, PDFRadioGroup, rgb, degrees } from "pdf-lib";
import { textFont } from "./font.ts";
export type MarkKind = "text" | "pen" | "highlight" | "rectangle" | "image";
export interface Mark {id:string;page:number;kind:MarkKind;x:number;y:number;w:number;h:number;text:string;size:number;color:string;data?:string;points?:[number,number][]}
export interface FormValue {name:string;kind:"text"|"checkbox"|"choice";value:string|boolean;options?:string[]}
export async function readForms(bytes:Uint8Array):Promise<FormValue[]>{const doc=await PDFDocument.load(bytes);return doc.getForm().getFields().flatMap<FormValue>(f=>f instanceof PDFTextField?[{name:f.getName(),kind:"text" as const,value:f.getText()||""}]:f instanceof PDFCheckBox?[{name:f.getName(),kind:"checkbox" as const,value:f.isChecked()}]:f instanceof PDFDropdown?[{name:f.getName(),kind:"choice" as const,value:f.getSelected()[0]||"",options:f.getOptions()}]:f instanceof PDFRadioGroup?[{name:f.getName(),kind:"choice" as const,value:f.getSelected()||"",options:f.getOptions()}]:[]);}
// Coordinates are normalized against the visible, rotated crop box.
export function screenPoint(box:{x:number;y:number;width:number;height:number},rotation:number,x:number,y:number):[number,number]{const {width:w,height:h}=box;const angle=((rotation%360)+360)%360;const p:[number,number]=angle===90?[y*w,x*h]:angle===180?[(1-x)*w,y*h]:angle===270?[(1-y)*w,(1-x)*h]:[x*w,(1-y)*h];return [box.x+p[0],box.y+p[1]];}
export async function editPdf(bytes:Uint8Array,marks:Mark[],fields:FormValue[],flatten:boolean){const doc=await PDFDocument.load(bytes);const font=await textFont(doc,marks.filter(m=>m.kind==="text").map(m=>m.text).join("")+fields.map(f=>String(f.value)).join(""));const form=doc.getForm();for(const field of fields){const f=form.getField(field.name);if(f instanceof PDFTextField)f.setText(String(field.value));if(f instanceof PDFCheckBox)field.value?f.check():f.uncheck();if(f instanceof PDFDropdown&&field.value)f.select(String(field.value));if(f instanceof PDFRadioGroup&&field.value)f.select(String(field.value));}
 for(const m of marks){const page=doc.getPage(m.page-1);const box=page.getCropBox();const rotation=((page.getRotation().angle%360)+360)%360;const viewWidth=rotation%180?box.height:box.width;const viewHeight=rotation%180?box.width:box.height;const point=(x:number,y:number)=>screenPoint(box,rotation,x,y);const c=m.color.match(/\w\w/g)!.map(v=>parseInt(v,16)/255);const color=rgb(c[0],c[1],c[2]);const [x,y]=point(m.x,m.y);
 if(m.kind==="text")page.drawText(m.text,{x,y,size:m.size,font,color,rotate:degrees(rotation)});
 else if(m.kind==="image"&&m.data){const image=m.data.startsWith("data:image/png")?await doc.embedPng(m.data):await doc.embedJpg(m.data);const [ix,iy]=point(m.x,m.y+m.h);page.drawImage(image,{x:ix,y:iy,width:m.w*viewWidth,height:m.h*viewHeight,rotate:degrees(rotation)});}
 else if(m.kind==="pen"){const pts=m.points||[];for(let i=1;i<pts.length;i++){const a=point(...pts[i-1]),b=point(...pts[i]);page.drawLine({start:{x:a[0],y:a[1]},end:{x:b[0],y:b[1]},thickness:2,color});}}
 else {const a=point(m.x,m.y+m.h),b=point(m.x+m.w,m.y);page.drawRectangle({x:Math.min(a[0],b[0]),y:Math.min(a[1],b[1]),width:Math.abs(b[0]-a[0]),height:Math.abs(b[1]-a[1]),color:m.kind==="highlight"?color:undefined,borderColor:m.kind==="rectangle"?color:undefined,borderWidth:2,opacity:m.kind==="highlight"?0.3:1});}}
 if(form.getFields().length)form.updateFieldAppearances(font);if(flatten&&form.getFields().length)form.flatten();return doc.save();}
