import { useEffect, useRef, useState } from "react";
import { useLocation } from "react-router-dom";
import { UploadCloud } from "lucide-react";
import { validateFiles, friendlyError } from "../lib/importFiles";
import { useDocumentStore } from "../store/useDocumentStore";
interface Props {accept:string;multiple?:boolean;label:string;hint:string;onFiles:(files:File[])=>void}
export function Dropzone({accept,multiple=false,label,hint,onFiles}:Props){const input=useRef<HTMLInputElement>(null);const callback=useRef(onFiles);useEffect(()=>{callback.current=onFiles;},[onFiles]);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const pending=useDocumentStore(s=>s.pending);const current=useDocumentStore(s=>s.current);const location=useLocation();const validate=async(files:File[])=>{setBusy(true);setError("");try{const valid=await validateFiles(files,accept,multiple);callback.current(valid);}catch(e){setError(friendlyError(e));}finally{setBusy(false);}};
 useEffect(()=>{if(pending?.path!==location.pathname)return;const file=pending.file;useDocumentStore.getState().clearPending();void validate([file]);},[pending?.id,location.pathname]);
 const compatible=current&&(accept.includes(current.type)||accept.includes("image/*")&&current.type.startsWith("image/"));
 return <div><div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)void validate(Array.from(e.dataTransfer.files));}}><button className="w-full py-3 text-center" disabled={busy} onClick={()=>input.current?.click()}><UploadCloud className="mx-auto mb-2 text-accent"/><strong>{busy?"Checking file…":label.replace(/^Drop.*here or click to browse$/,accept.includes("image")?"Choose files":"Choose a PDF")}</strong><span className="block mt-2 text-sm text-muted">{hint}</span></button><input ref={input} type="file" accept={accept} multiple={multiple} className="sr-only" aria-label="Choose files" onChange={e=>{void validate(Array.from(e.target.files??[]));e.target.value="";}}/></div>{compatible&&!pending&&<button className="btn-secondary w-full mt-2 truncate" onClick={()=>void validate([current])}>Use current: {current.name}</button>}{error&&<p role="alert" className="mt-2 text-sm text-bad">{error}</p>}</div>}
